kibana:
  image: kibana
  links:
    - elasticsearch
  ports:
    - "5601:5601"

elasticsearch:
  image: elasticsearch
  volumes:
    - "./esdata:/usr/share/elasticsearch/data"
  ports:
    - "9300:9300"
    - "9200:9200"
