input:
  file:
  - file: "./input.txt"
    type: "input-file"
  syslog-server:
  - port: "5539"
    protocol: "tcp"
    type: "syslog-server"
processing:
  regex:
  - regex: "^(this)*"
    mapping: "(1) thing"
    name: "tester-1"
  - regex: "^(foo)*"
    mapping: "(1)(1)"
    name: "tester-2"
output:
  file:
  - file: "./output.txt"
  - file: "./output2.txt"
  elasticsearch:
  - url: "http://127.0.0.1:9200"
  - url: "http://127.0.0.1:9201"
